// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nex.domain;

import com.nex.domain.CulturalObject;
import javax.persistence.Entity;
import javax.persistence.Table;

privileged aspect CulturalObject_Roo_Jpa_Entity {
    
    declare @type: CulturalObject: @Entity;
    
    declare @type: CulturalObject: @Table(name = "cultural_obj");
    
}
