// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nex.domain.common;

import com.nex.domain.common.Test;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Test_Roo_Configurable {
    
    declare @type: Test: @Configurable;
    
}
