// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nex.domain.common;

import com.nex.domain.common.Test;
import javax.persistence.Entity;
import javax.persistence.Table;

privileged aspect Test_Roo_Jpa_Entity {
    
    declare @type: Test: @Entity;
    
    declare @type: Test: @Table(name = "test_table");
    
}
