// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nex.domain.common;

import com.nex.domain.common.Test;

privileged aspect Test_Roo_JavaBean {
    
    public Long Test.getId() {
        return this.id;
    }
    
    public void Test.setId(Long id) {
        this.id = id;
    }
    
    public String Test.getText() {
        return this.text;
    }
    
    public void Test.setText(String text) {
        this.text = text;
    }
    
}
