// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nex.domain.test;

import com.nex.domain.localizedfield.LocalizedField;
import com.nex.domain.test.DamageType;
import java.util.List;

privileged aspect DamageType_Roo_JavaBean {
    
    public Long DamageType.getId() {
        return this.id;
    }
    
    public void DamageType.setId(Long id) {
        this.id = id;
    }
    
    public List<LocalizedField> DamageType.getLocalizedTexts() {
        return this.localizedTexts;
    }
    
    public void DamageType.setLocalizedTexts(List<LocalizedField> localizedTexts) {
        this.localizedTexts = localizedTexts;
    }
    
}
