// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nex.domain.test;

import com.nex.domain.test.DamageTypeText;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DamageTypeText_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext(unitName = "puCah")
    transient EntityManager DamageTypeText.entityManager;
    
    public static final EntityManager DamageTypeText.entityManager() {
        EntityManager em = new DamageTypeText().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long DamageTypeText.countDamageTypeTexts() {
        return entityManager().createQuery("SELECT COUNT(o) FROM DamageTypeText o", Long.class).getSingleResult();
    }
    
    public static List<DamageTypeText> DamageTypeText.findAllDamageTypeTexts() {
        return entityManager().createQuery("SELECT o FROM DamageTypeText o", DamageTypeText.class).getResultList();
    }
    
    public static DamageTypeText DamageTypeText.findDamageTypeText(Long id) {
        if (id == null) return null;
        return entityManager().find(DamageTypeText.class, id);
    }
    
    public static List<DamageTypeText> DamageTypeText.findDamageTypeTextEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM DamageTypeText o", DamageTypeText.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void DamageTypeText.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void DamageTypeText.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            DamageTypeText attached = DamageTypeText.findDamageTypeText(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void DamageTypeText.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void DamageTypeText.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public DamageTypeText DamageTypeText.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        DamageTypeText merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
