// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nex.domain.test;

import com.nex.domain.test.DamageType;
import com.nex.domain.test.DamageTypeText;

privileged aspect DamageTypeText_Roo_JavaBean {
    
    public Long DamageTypeText.getId() {
        return this.id;
    }
    
    public void DamageTypeText.setId(Long id) {
        this.id = id;
    }
    
    public DamageType DamageTypeText.getLocalizable() {
        return this.localizable;
    }
    
    public void DamageTypeText.setLocalizable(DamageType localizable) {
        this.localizable = localizable;
    }
    
}
