// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nex.domain.test;

import com.nex.domain.test.DamageType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Version;

privileged aspect DamageType_Roo_Jpa_Entity {
    
    declare @type: DamageType: @Entity;
    
    declare @type: DamageType: @Table(name = "damagetypes");
    
    @Version
    @Column(name = "version")
    private Integer DamageType.version;
    
    public Integer DamageType.getVersion() {
        return this.version;
    }
    
    public void DamageType.setVersion(Integer version) {
        this.version = version;
    }
    
}
