// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nex.domain.test;

import com.nex.domain.test.DamageTypeText;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Version;

privileged aspect DamageTypeText_Roo_Jpa_Entity {
    
    declare @type: DamageTypeText: @Entity;
    
    declare @type: DamageTypeText: @Table(name = "damagetypes_text");
    
    @Version
    @Column(name = "version")
    private Integer DamageTypeText.version;
    
    public Integer DamageTypeText.getVersion() {
        return this.version;
    }
    
    public void DamageTypeText.setVersion(Integer version) {
        this.version = version;
    }
    
}
