// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nex.domain.test;

import com.nex.domain.test.DamageTypeText;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect DamageTypeText_Roo_Configurable {
    
    declare @type: DamageTypeText: @Configurable;
    
}
